CREATE TABLE store(
	ID SERIAL UNIQUE PRIMARY KEY, 
	name VARCHAR(90) NOT NULL
);

CREATE TABLE user_p(
	ID SERIAL UNIQUE PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(70) NOT NULL
);

CREATE TABLE product(
	ID SERIAL UNIQUE PRIMARY KEY,
	name VARCHAR(60) NOT NULL
);

CREATE TABLE necessity(
	user_id INTEGER REFERENCES  user_p(id) ON DELETE CASCADE,
	product_id INTEGER REFERENCES product(id) ON DELETE CASCADE,
	store_id INTEGER REFERENCES store(id) ON DELETE CASCADE, 
	PRIMARY KEY (user_id,product_id)
);

